server:
    port: 8603
spring:
   data.mongodb:
      host: localhost
      port: 27017
      database: metadatatemplates
      
---

spring.profiles: prod
      
spring:
   data.mongodb:
      host: 193.52.225.51