server:
    port: 8603
spring:
   application.name: Metadata templates
   data.mongodb:
      host: localhost
      port: 27017
      database: metadatatemplates
   boot:
       admin:
           client:
               url: http://127.0.0.1:9999      
info:
    description: https://www.sedoo.fr/metadatatemplates
    code:
        front: none
        back: https://github.com/aeris-data/aeris-metadatatemplate-rest
    folders: none
    database:
        type: mongo
        location: SEDUR
    archive: none

        
endpoints:
    enabled: true
    health:
        enabled: true
management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
        health:
            show-details: "ALWAYS"
            northstar:
                cacheup: 240
                cachedown: 120   
---

spring.profiles: prod

info:
    hosting:
        machine: TWODOO
        installationFolder: /export1/metadatatemplates

spring:
   boot:
       admin:
           client:
               url: https://monitoring.sedoo.fr
               boot:
               instance:
                   service-base-url: https://services.sedoo.fr/metadatatemplate
                   service-path: /metadatatemplate
   data.mongodb:
      host: 193.52.225.51